configs:
  cm:
    url: https://argocd.company.co
    dex.config: |
      logger:
        level: debug
      connectors:
        - type: ldap
          id: my-ldap
          name: LDAP
          config:
            host: "gi.hold:636"
            insecureSkipVerify: true
            bindDN: CN=NNNNN\, MMMM (HIT),OU=HIT-Users,OU=HIT,OU=GIG-Hold,DC=gi,DC=hold
            bindPW: *********
            usernamePrompt: Username
            userSearch:
              baseDN: "OU=HIT-Users,OU=HIT,OU=GIG-Holdings,DC=gi,DC=hold"
              filter: "(objectClass=top)"
              username: sAMAccountName
              idAttr: sAMAccountName
              emailAttr: mail
              nameAttr: name
                #preferredUsernameAttr: uid
            groupSearch:
              baseDN: "OU=HIT-Users,OU=HIT,OU=GIG-Holdings,DC=gi,DC=hold"
              filter: "(objectClass=top)"
              userMatchers:
              - userAttr: sAMAccountName
                groupAttr: member
                  #userAttr: DN
                  #groupAttr: member
              nameAttr: cn

dex:
  logLevel: "debug"
  extraArgs: 
    - --disable-tls
server:
  extraArgs:
    - --dex-server=http://argo-cd-argocd-dex-server:5556
    - --dex-server-plaintext                
